from typing import Optional, Callable, Any, Hashable, Iterable


KeyFunc = Callable[[Any], Hashable]
def uniq(seq: Iterable[Any], key: Optional[KeyFunc]) -> list: ...
def tolist(obj: Any) -> list: ...
def flatten(seq: Iterable[Any]) -> Iterable[Any]: ...
