from typing import Callable, Any


AnyCallable = Callable[..., Any]

def timeout(seconds: int, error_message: str) -> Callable[[AnyCallable], AnyCallable]: ...
def trace(func: AnyCallable) -> AnyCallable: ...
def memoize(func: AnyCallable) -> AnyCallable: ...
def memoize_when_activated(func: AnyCallable) -> AnyCallable: ...
def super_len(obj: Any) -> int: ...