import collections
from typing import Iterable, Tuple, Any, Mapping, Dict, Union


class CaseInsensitiveDict(collections.MutableMapping):
    _store = ... # type: dict
    def __init__(self, data: dict=None, **kwargs) -> None: ...
    def lower_items(self) -> Iterable[Tuple[str, Any]]: ...

def pick(mapping: Mapping[Any, Any], keys: Union[Any, Iterable[Any]]) -> Dict[Any, Any]: ...
def omit(mapping: Mapping[Any, Any], keys: Union[Any, Iterable[Any]]) -> Dict[Any, Any]: ...
