from collections.abc import MutableMapping
from typing import Iterable, Tuple, Any, Mapping, Dict, Union


class CaseInsensitiveDict(MutableMapping):
    _store = ... # type: dict
    def __init__(self, data: dict=None, **kwargs) -> None: ...
    def lower_items(self) -> Iterable[Tuple[str, Any]]: ...

def pick(mapping: Mapping[Any, Any], keys: Union[Any, Iterable[Any]]) -> Dict[Any, Any]: ...
def omit(mapping: Mapping[Any, Any], keys: Union[Any, Iterable[Any]]) -> Dict[Any, Any]: ...
def get_path(mapping: Any, path: Union[Any, Iterable[Any]], default: Any=None, separator: str='.') -> Any: ...
def set_path(mapping: MutableMapping[Any, Any], path: Union[Any, Iterable[Any]], value: Any, separator: str='.') -> MutableMapping[Any, Any]: ...
def deep_merge(*mappings: Mapping[Any, Any]) -> Dict[Any, Any]: ...
