from typing import Callable, Any, Hashable, Iterable


KeyFunc = Callable[[Any], Hashable]
def uniq(seq: Iterable[Any], key: KeyFunc=None) -> list: ...
def tolist(obj: Any) -> list: ...
def flatten(seq: Iterable[Any]) -> Iterable[Any]: ...
