from typing import ContextManager, List


def cd(path: str) -> ContextManager[None]: ...
def is_super_path(path1: str, path2: str) -> bool: ...
def normjoin(path: str, *paths: List(str)) -> str: ...
def filename(path: str) -> str: ...
def fileexe(path: str) -> str: ...
