"""Stubs for cmd"""
from typing import Optional, Tuple, List


class TimeoutExpired(Exception):

    def __init__(self, cmd: str, timeout: int, output: Optional[str]=..., stderr: Optional[str]=...) -> None: ...

def run(cmd: str, shell: bool=..., env: Optional[dict]=..., timeout: int=..., timeinterval: int=...) -> Tuple[int, str]: ...
def run_with_en_env(cmd: str, shell: bool=..., env: Optional[dict]=..., timeout: int=..., timeinterval: int=...) -> Tuple[int, str]: ...
def terminate(pid: int) -> None: ...
def cmdline_argv() -> List: ...
