from typing import Any


def boolean(obj: Any) -> bool: ...
def bin2oct(x: str) -> str: ...
def bin2dec(x: str) -> int: ...
def bin2hex(x: str) -> str: ...
def oct2bin(x: str) -> str: ...
def oct2dec(x: str) -> int: ...
def oct2hex(x: str) -> str: ...
def dec2bin(x: int) -> str: ...
def dec2oct(x: int) -> str: ...
def dec2hex(x: int) -> str: ...
def hex2bin(x: str) -> str: ...
def hex2oct(x: str) -> str: ...
def hex2dec(x: str) -> int: ...
